version: '3.8'
services:
  nginx:
    image: nginx:stable-alpine3.20-perl
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/access1.log:/var/log/nginx/access1.log
    networks:
      - network1

networks:
  network1:
    name: docker_network
    external: true