version: '3.8'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: es
    # mem_limit: 1g
    environment: 
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    command: >
      bash -c "if (! elasticsearch-plugin list | grep analysis-icu); then elasticsearch-plugin install analysis-icu ; fi
      && /usr/local/bin/docker-entrypoint.sh elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      # nofile:
      #   soft: 65536
      #   hard: 65536
    volumes:
      - type: bind
        source: ./data
        target: /usr/share/elasticsearch/data
      - type: bind
        source: ./config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      - "network1"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=50s || exit 1"]
      interval: 1s
      timeout: 5s
      retries: 120
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    ports:
      - 5601:5601
    restart: on-failure
    depends_on:
      - es
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - network1

  nginx:
    image: nginx:stable-alpine3.20-perl
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/access1.log:/var/log/nginx/access1.log
    networks:
      - network1

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.12.0
    container_name: filebeat
    # mem_limit: 1g
    environment: 
      - BEAT_LOG_OPTS=-d elasticsearch
    volumes:
      - ./data:/usr/share/filebeat/data:rw
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ../nginx/config/access1.log:/usr/share/filebeat/logs/access.log
    ports:
      - 5040:5040
    networks:
      - "network1"
    healthcheck:
      test: ["CMD", "filebeat", "test", "output"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - nginx
      - es

  logstash:
    build:
      context: .
      dockerfile: Dockerfile
    image: logstash:8.12.0-custom
    container_name: logstash
    # mem_limit: 1g
    volumes:
      - ./config:/usr/share/logstash/config
      - ./pipeline:/usr/share/logstash/pipeline
    ports:
      - 5044:5044
      - 50000:50000/tcp
      - 50000:50000/udp
      - 9600:9600
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
      # LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
    depends_on:
      - es
      - filebeat
    restart: unless-stopped
    networks:
      - network1

networks:
  network1:
    name: docker_network
    external: true

