version: '3.8'
services:
  nginx:
    image: nginx:stable-alpine3.20-perl
    container_name: nginx1
    ports:
      - 81:80
    volumes:
      - nginx-data:/usr/share/nginx/html
    networks:
      - network1

networks:
  network1:
    name: docker_network
    external: true

volumes:
  nginx-data:
    name: nginx-data
    external: true