version: '3.8'
services:
  logstash:
    build:
      context: .
      dockerfile: Dockerfile
    # image: docker.elastic.co/logstash/logstash:8.12.0
    image: logstash:8.12.0-custom
    container_name: logstash
    # mem_limit: 1g
    volumes:
      - ./config:/usr/share/logstash/config
      - ./pipeline:/usr/share/logstash/pipeline
    ports:
      - 5044:5044
      - 50000:50000/tcp
      - 50000:50000/udp
      - 9600:9600
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
      # LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
    # depends_on:
    #   - es
    restart: unless-stopped
    networks:
      - network1

networks:
  network1:
    name: docker_network
    external: true

