# filebeat.config:
#   modules:
#     path: ${path.config}/modules.d/*.yml
#     reload.enabled: false

# processors:
#   - add_cloud_metadata: ~
#   - add_docker_metadata: ~

# # output.elasticsearch:
# #   hosts: 'es:9200'
# #   username: ''
# #   password: ''
# #   template:
# #     name: "filebeat"
# #     path: "fields.yml"
# #     overwrite: false
# #   protocol: "http"

# - module: logstash
#   # logs
#   log:
#     enabled: true
#   var.paths:
#     - /usr/share/filebeat/logs/access.log

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/logs/access.log  # Path to Nginx access logs

# Logstash output configuration
output.logstash:
  hosts: ["logstash:5044"]   # Address of Logstash

logging.level: debug
